### ISSUE TITLE
Pay-to-play?

### ISSUE THREAD

**Issue by nikita-tkachov** [sibelius/relay-workshop-old#6]
Hey,

Noticed that this repository is now closed source and requiring a donation to your Patreon to access.

I don't think this is very cool of you, especially because the last time I visited the repository, most of the code was taken directly from the [Relay Issue Tracker](https://github.com/relayjs/relay-examples/tree/main/issue-tracker), with modified examples.

This repository is also brought up many times in the [Relay Repository](https://github.com/facebook/relay/issues?q=relay-workshop) [here](https://github.com/facebook/relay/issues/3351), [here](https://github.com/facebook/relay/issues/3352) and [here](https://github.com/facebook/relay/pull/3426). There's even a [pull request to put it in the main relay documentation site for examples](https://github.com/facebook/relay/pull/3464).

It also looks like all of the commits have been pretty much wiped, so I'm not 100% sure what's going on but personally I don't like the idea of new people trying to figure out how to use Relay, and when searching the Relay repository, they can find many comments by you, linking directly here.

It seems that this was changed recently and I'm not trying to be all up in your business (make your money, king/queen), but if you're gonna go with this approach, it would be nice if you deleted all of your comments linking back here or opened the repository back up.

Thanks,
Nick

**Comment by sibelius** [comment]
You can get access to the code for only 5usd, very cheap

You can also open discussions here https://github.com/sibelius/relay-workshop/discussions for free

the only part that Relay Workshop uses of relay issue tracker is the routing

it has 12 useful exercises to make you really learn relay

the was tons of work and my time to get to this shape.

you can always learn Relay for free by yourself

**Comment by nikita-tkachov** [comment]
@sibelius 

Hey, thanks for the response.

I understand that it's a lot of work to maintain something that's open source, I get that.

But, there's hundreds of thousands of open source repositories that (arguably) provide more value, and do it without getting paid a dime. If you're looking to make some money on the side, you can always create an [Open Collective](https://opencollective.com/)

How would you feel about Facebook charging $5 for documentation about Relay?

I would totally understand if you created a new repository with new code and everything, but every single comment you posted links back to this one, which is now behind a paywall.

I would also like to point out that the issue-tracker repository license explicitly states that [The examples provided by Facebook are for non-commercial testing and evaluation purposes only](https://github.com/relayjs/relay-examples/blob/main/LICENSE.md). Even if you "only" use the routing code, it's still a property of Facebook, and you can't just sell it back to other people (maybe you can but that seems highly unethical).

**Comment by sibelius** [comment]
I will replace the router to use react-router-dom 

Tks
